spring.application.name=jtaskboard

spring.datasource.url=jdbc:postgresql://localhost:5432/jtaskboard
spring.datasource.username=jtaskboard
spring.datasource.password=jtaskboard

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.time-zone=UTC

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

